### ISSUE TITLE
Problem using microsoft oauth2 as provider because of dynamic issuer

### ISSUE THREAD

**Issue by FLX-0x00** [omniauth/omniauth_openid_connect#166]
Hey community / maintainers - Want to reach you out because I want to implement Microsoft Entra with OpenID Connect into my Rails App using the gem  omniauth_openid_connect with rodauth-omniauth.

I have come up with the following config
```ruby
    omniauth_provider :openid_connect, {
      name: :microsoft,
      scope: [:openid, :email],
      issuer: 'https://login.microsoftonline.com/{tenantid}/v2.0', # not sure - this is my stucking part
      client_options: {
        host: 'login.microsoftonline.com',
        authorization_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        token_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        userinfo_endpoint: 'https://graph.microsoft.com/oidc/userinfo',
        jwks_uri: 'https://login.microsoftonline.com/common/discovery/v2.0/keys',
        end_session_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/logout',
        identifier: Rails.application.credentials[:identifier],
        secret: Rails.application.credentials[:oauth_secret],
        redirect_uri: Rails.application.config.microsoft_openid_connect_redirect_uri
      }
    }
```

The authentication works until the callback phase:
```
02:24:16 web.1  | E, [2023-11-29T02:24:16.168085 #271321] ERROR -- omniauth: (microsoft) Authentication failure! Invalid ID token: Issuer does not match: OpenIDConnect::ResponseObject::IdToken::InvalidIssuer, Invalid ID token: Issuer does not match
```
The corresponding code is in
`vendor/bundle/ruby/3.2.0/gems/openid_connect-2.2.0/lib/openid_connect/response_object/id_token.rb#L26`

After debugging I noticed that the issuer that is expected changes if another account (of another org for example) logs into (this should be the `tenantid`. The Microsoft documentation https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration says, that the issuer is determined by the `tenantid` of the users account. This is where I hopefully overthinked or overlooked something. How can I get a dynamic issuer value to my provider config? Hope anyone can understand the current issue.

Cheers!

**Comment by bufferoverflow** [comment]
I never tested with common, only with a specific tenant. There you must use the tenant specific endpoints all over or set `discovery: true` to avoid the `client_options`, see https://docs.gitlab.com/ee/integration/azure.html

**Comment by FLX-0x00** [comment]
Hey thank you for the fast response. I was not able to get to a successful configuration where discovery works. So you mean that I have to set the issuer to the url with my tenant id? I was reading through the documentation and every documents I found uses the common one as this specifies if users can authenticate with private accounts or not. But I will give it a try.

**Comment by FLX-0x00** [comment]
If i set the tenant id in the issuer field and discovery to true, than nobody except permitted users can login. `The selected user account does not exist in the "Microsoft Services" client and cannot access the "TENANTID" application in this client. The account must first be added to the client as an external user. Use a different account.`

**Comment by FLX-0x00** [comment]
Or is this a problem related to the gem `openid_connect`? Because I have to use common as there is no specific tenant i prefer. Only want to use Microsoft as openid provider to create an account on my end or login.

**Comment by FLX-0x00** [comment]
I have seen in the openid_connect gem that there is a way when initializing OpenID to ignore the issuer validation. Maybe this is a way in this specific scenario if this gem here supports this flag. Now I have monkey patched the validation from exact match to regex. Not ideal but do the job without loosing security

**Comment by FLX-0x00** [comment]
maybe this helps:

https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri

**Comment by bufferoverflow** [comment]
@FLX-0x00 I'm using this gem as part of GitLab since about a year with Entra ID and before with another IdP, works smooth.  As [written above](https://github.com/omniauth/omniauth_openid_connect/issues/166#issuecomment-1831313214): `There you must use the tenant specific endpoints all over or set discovery: true to avoid the client_options, see https://docs.gitlab.com/ee/integration/azure.html`

**Comment by felixstorm** [comment]
I have a very similar problem - I also need to use the common endpoint (`https://login.microsoftonline.com/common/v2.0`) since we have users from multiple Azure tenants and I already do use `"discovery" => true` but I still get the error "Issuer is not a valid url and issuer mismatch".

When looking at the discovery document from Azure, the issuer gets specified as `"issuer": "https://login.microsoftonline.com/{tenantid}/v2.0"`, i.e. it literally contains the term `/{tenantid}/`. This might be the reason for the "not a valid url" part of the error message. And when looking at the token returned, it contains the full tenant id (`https://login.microsoftonline.com/810017af-c1d4-4a3b-9e18-.../v2.0`) - this might be the reason for the second part of the error message ("issuer mismatch").

@bufferoverflow I am open for any suggestions, but I honestly do not see a way to use this gem with users from multiple Azure/Entra Id tenants. Or is there anything else I could do or try to make it work?  
My config in general seems to be fine as it works without problems if I exchange the `common` in the issuer with an actual tenant id, but this is not an option since is prevents users from other tenants from logging in.

My config (also GitLab):
```ruby
gitlab_rails['omniauth_providers'] = [
  {
    "name"  => "azure_oauth2",
    "label" => "Microsoft Entra ID",
    "args" => {
      "name"               => "azure_oauth2",
      "strategy_class"     => "OmniAuth::Strategies::OpenIDConnect",
      "issuer"             => "https://login.microsoftonline.com/common/v2.0",
      "discovery"          => true,
      "scope"              => ["openid", "profile", "email"],
      "pkce"               => true,
      "uid_field"          => "oid",
      "client_options" => {
        "identifier"   => "...",
        "secret"       => "...",
        "redirect_uri" => "https://gitlab.example.com/users/auth/azure_oauth2/callback",
      }
    }
  }
]
```

In case anybody else has the same problem and sees this issue: I had to resort to use `OmniAuth::Strategies::AzureActivedirectoryV2` (https://docs.gitlab.com/ee/integration/azure.html) instead which seems to work fine also for users from multiple tenants - even though I would have very much preferred to use this gem instead.

**Comment by FLX-0x00** [comment]
@felixstorm Totally forgot to mention this but yes - we have switched to `omniauth-azure-activedirectory-v2` gem and it works out of the box.

**Comment by bufferoverflow** [comment]
@felixstorm as I see within https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration the {tenantid} placeholder is used. So for this case please try with the config mentioned within the issue description or below, but set your tenantid within the issuer as `https://login.microsoftonline.com/810017af-c1d4-4a3b-9e18-.../v2.0`  and using the tenantid were you registered the app:

```json
omniauth_provider :openid_connect, {
      name: :microsoft,
      scope: [:openid, :email],
      issuer: 'https://login.microsoftonline.com/810017af-c1d4-4a3b-9e18-.../v2.0', # not sure - this is my stucking part
      client_options: {
        host: 'login.microsoftonline.com',
        authorization_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        token_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        userinfo_endpoint: 'https://graph.microsoft.com/oidc/userinfo',
        jwks_uri: 'https://login.microsoftonline.com/common/discovery/v2.0/keys',
        end_session_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/logout',
        identifier: Rails.application.credentials[:identifier],
        secret: Rails.application.credentials[:oauth_secret],
        redirect_uri: Rails.application.config.microsoft_openid_connect_redirect_uri
      }
    }
```

I suspect autodiscovery does not work as the issuer is tenant specific.

**Comment by bufferoverflow** [comment]
ok, @felixstorm @FLX-0x00 I just verified and it works smooth. Here is the config I used to verify within my gdk:

```yaml
    - { name: "openid_connect_aad",
        label: "Microsoft Entra ID",
        args: {
          name: "openid_connect_aad",
          strategy_class: "OmniAuth::Strategies::OpenIDConnect",
          scope: ["openid","profile","email"],
          response_type: "code",
          issuer: "https://login.microsoftonline.com/*****************************************/v2.0",
          client_auth_method: "query",
          client_options: {
            identifier: "*****************************************",
            secret: "*****************************************",
            authorization_endpoint: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            token_endpoint: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo",
            jwks_uri: "https://login.microsoftonline.com/common/discovery/v2.0/keys",
            end_session_endpoint: "https://login.microsoftonline.com/common/oauth2/v2.0/logout",
            redirect_uri: "https://example.com/users/auth/openid_connect_aad/callback"
          }
        }
      }
```

I tested `organizations` beside of `common`, works as well. For further details regarding the differences of those, see https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri
